# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='translation',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
